services:
  crypto_tracker:
    container_name: crypto_tracker
    image: crypto_tracker:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgres://harry:pass123@db:5432/postgres?sslmode=disable' #'realPostgres://userOfDatabase:passwordOfDatabase'
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:18
    environment:
      POSTGRES_USER: harry
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}